### ISSUE TITLE
Upgrade to django-sodar-core v0.11.0

### ISSUE THREAD

**Issue by mikkonie** [bihealth/kiosc-server#151]
This upgrade is required because the API is no longer 100% compatible with v0.10.

Will also upgrade general dependencies to match v0.11.0.

The current version used is `v0.10.5+10.g36ed460`.

## Tasks

- [x] Upgrade dependencies
- [x] Fix `wheel` installation in CI
- [x] Update Python versions (3.7 no longer supported)
- [x] Upgrade to Postgres v11
- [x] Update Django settings as needed
- [x] Replace `get_plugin_name_by_id()` if used
- [x] ~~Ensure search results DataTables look ok~~ (search not implemented)
- [x] Replace `Project.has_public_children()` with `Project has_public_children` if used
- [x] Ensure UI tests work after selenium upgrade
- [x] Update `get_event_description()` calls if used
- [x] Update `app_search_data` to `app_results` in seach tests if used
- [x] Remove taskflow references
- [x] Remove usages of `Project.submit_status` if used
- [x] Update `django-autocomplete-light` usage if used
- [x] Update login template if overridden
- [x] Update helper scripts where applicable
- [x] Reinstall versioneer
- [x] Remove the redundant "extra link" from the titlebar :) (or replace with manual link?)
- [x] Update default footer

**Comment by mikkonie** [comment]
Optional things left out from this upgrade, which I would recommend someone to look at:

- Update logging setup to match the current nice one in SODAR Core (see `config/settings/base.py`)
